@startwbs
!include https://raw.githubusercontent.com/patrik-csak/one-dark-plantuml-theme/v1.0.1/theme.puml
'skinparam monochrome reverse
+ Produtos
	+ Cesta
		+ Tamanhos
			+ Pequeno
			+ Grande
			+ Médio
		+ Tipos
			+ Surpresa
				+ Avulso
	+ Sacola
		+ Avulso
@endwbs
